	nios_hps_system u0 (
		.clk_clk                            (<connected-to-clk_clk>),                            //                     clk.clk
		.hps_0_ddr_mem_a                    (<connected-to-hps_0_ddr_mem_a>),                    //               hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                   (<connected-to-hps_0_ddr_mem_ba>),                   //                        .mem_ba
		.hps_0_ddr_mem_ck                   (<connected-to-hps_0_ddr_mem_ck>),                   //                        .mem_ck
		.hps_0_ddr_mem_ck_n                 (<connected-to-hps_0_ddr_mem_ck_n>),                 //                        .mem_ck_n
		.hps_0_ddr_mem_cke                  (<connected-to-hps_0_ddr_mem_cke>),                  //                        .mem_cke
		.hps_0_ddr_mem_cs_n                 (<connected-to-hps_0_ddr_mem_cs_n>),                 //                        .mem_cs_n
		.hps_0_ddr_mem_ras_n                (<connected-to-hps_0_ddr_mem_ras_n>),                //                        .mem_ras_n
		.hps_0_ddr_mem_cas_n                (<connected-to-hps_0_ddr_mem_cas_n>),                //                        .mem_cas_n
		.hps_0_ddr_mem_we_n                 (<connected-to-hps_0_ddr_mem_we_n>),                 //                        .mem_we_n
		.hps_0_ddr_mem_reset_n              (<connected-to-hps_0_ddr_mem_reset_n>),              //                        .mem_reset_n
		.hps_0_ddr_mem_dq                   (<connected-to-hps_0_ddr_mem_dq>),                   //                        .mem_dq
		.hps_0_ddr_mem_dqs                  (<connected-to-hps_0_ddr_mem_dqs>),                  //                        .mem_dqs
		.hps_0_ddr_mem_dqs_n                (<connected-to-hps_0_ddr_mem_dqs_n>),                //                        .mem_dqs_n
		.hps_0_ddr_mem_odt                  (<connected-to-hps_0_ddr_mem_odt>),                  //                        .mem_odt
		.hps_0_ddr_mem_dm                   (<connected-to-hps_0_ddr_mem_dm>),                   //                        .mem_dm
		.hps_0_ddr_oct_rzqin                (<connected-to-hps_0_ddr_oct_rzqin>),                //                        .oct_rzqin
		.hps_0_h2f_loan_io_in               (<connected-to-hps_0_h2f_loan_io_in>),               //       hps_0_h2f_loan_io.in
		.hps_0_h2f_loan_io_out              (<connected-to-hps_0_h2f_loan_io_out>),              //                        .out
		.hps_0_h2f_loan_io_oe               (<connected-to-hps_0_h2f_loan_io_oe>),               //                        .oe
		.hps_0_io_hps_io_sdio_inst_CMD      (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),      //                hps_0_io.hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0       (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),       //                        .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1       (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),       //                        .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK      (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),      //                        .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2       (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),       //                        .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3       (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),       //                        .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_gpio_inst_LOANIO49 (<connected-to-hps_0_io_hps_io_gpio_inst_LOANIO49>), //                        .hps_io_gpio_inst_LOANIO49
		.hps_0_io_hps_io_gpio_inst_LOANIO50 (<connected-to-hps_0_io_hps_io_gpio_inst_LOANIO50>), //                        .hps_io_gpio_inst_LOANIO50
		.hps_0_io_hps_io_gpio_inst_LOANIO55 (<connected-to-hps_0_io_hps_io_gpio_inst_LOANIO55>), //                        .hps_io_gpio_inst_LOANIO55
		.hps_0_io_hps_io_gpio_inst_LOANIO56 (<connected-to-hps_0_io_hps_io_gpio_inst_LOANIO56>), //                        .hps_io_gpio_inst_LOANIO56
		.i2c_peripheral_sda_in              (<connected-to-i2c_peripheral_sda_in>),              //          i2c_peripheral.sda_in
		.i2c_peripheral_scl_in              (<connected-to-i2c_peripheral_scl_in>),              //                        .scl_in
		.i2c_peripheral_sda_oe              (<connected-to-i2c_peripheral_sda_oe>),              //                        .sda_oe
		.i2c_peripheral_scl_oe              (<connected-to-i2c_peripheral_scl_oe>),              //                        .scl_oe
		.nios_7seg_export                   (<connected-to-nios_7seg_export>),                   //               nios_7seg.export
		.nios_buttons_export                (<connected-to-nios_buttons_export>),                //            nios_buttons.export
		.nios_header_conn_in_port           (<connected-to-nios_header_conn_in_port>),           //        nios_header_conn.in_port
		.nios_header_conn_out_port          (<connected-to-nios_header_conn_out_port>),          //                        .out_port
		.nios_i2cclk_export                 (<connected-to-nios_i2cclk_export>),                 //             nios_i2cclk.export
		.nios_i2cdat_in_port                (<connected-to-nios_i2cdat_in_port>),                //             nios_i2cdat.in_port
		.nios_i2cdat_out_port               (<connected-to-nios_i2cdat_out_port>),               //                        .out_port
		.nios_i2crw_export                  (<connected-to-nios_i2crw_export>),                  //              nios_i2crw.export
		.nios_leds_export                   (<connected-to-nios_leds_export>),                   //               nios_leds.export
		.nios_switches_export               (<connected-to-nios_switches_export>),               //           nios_switches.export
		.nios_uartrx_export                 (<connected-to-nios_uartrx_export>),                 //             nios_uartrx.export
		.nios_uarttx_export                 (<connected-to-nios_uarttx_export>),                 //             nios_uarttx.export
		.pll_0_sdram_clk                    (<connected-to-pll_0_sdram_clk>),                    //             pll_0_sdram.clk
		.reset_reset_n                      (<connected-to-reset_reset_n>),                      //                   reset.reset_n
		.sdram_controller_0_wire_addr       (<connected-to-sdram_controller_0_wire_addr>),       // sdram_controller_0_wire.addr
		.sdram_controller_0_wire_ba         (<connected-to-sdram_controller_0_wire_ba>),         //                        .ba
		.sdram_controller_0_wire_cas_n      (<connected-to-sdram_controller_0_wire_cas_n>),      //                        .cas_n
		.sdram_controller_0_wire_cke        (<connected-to-sdram_controller_0_wire_cke>),        //                        .cke
		.sdram_controller_0_wire_cs_n       (<connected-to-sdram_controller_0_wire_cs_n>),       //                        .cs_n
		.sdram_controller_0_wire_dq         (<connected-to-sdram_controller_0_wire_dq>),         //                        .dq
		.sdram_controller_0_wire_dqm        (<connected-to-sdram_controller_0_wire_dqm>),        //                        .dqm
		.sdram_controller_0_wire_ras_n      (<connected-to-sdram_controller_0_wire_ras_n>),      //                        .ras_n
		.sdram_controller_0_wire_we_n       (<connected-to-sdram_controller_0_wire_we_n>),       //                        .we_n
		.spi_peripheral_MISO                (<connected-to-spi_peripheral_MISO>),                //          spi_peripheral.MISO
		.spi_peripheral_MOSI                (<connected-to-spi_peripheral_MOSI>),                //                        .MOSI
		.spi_peripheral_SCLK                (<connected-to-spi_peripheral_SCLK>),                //                        .SCLK
		.spi_peripheral_SS_n                (<connected-to-spi_peripheral_SS_n>),                //                        .SS_n
		.uart_peripheral_rxd                (<connected-to-uart_peripheral_rxd>),                //         uart_peripheral.rxd
		.uart_peripheral_txd                (<connected-to-uart_peripheral_txd>),                //                        .txd
		.pll_1_65_clk                       (<connected-to-pll_1_65_clk>),                       //                pll_1_65.clk
		.pll_1_108_clk                      (<connected-to-pll_1_108_clk>),                      //               pll_1_108.clk
		.pll_1_86_clk                       (<connected-to-pll_1_86_clk>),                       //                pll_1_86.clk
		.pll_1_162_clk                      (<connected-to-pll_1_162_clk>),                      //               pll_1_162.clk
		.pll_1_144_clk                      (<connected-to-pll_1_144_clk>),                      //               pll_1_144.clk
		.nios_oscdivisor_export             (<connected-to-nios_oscdivisor_export>)              //         nios_oscdivisor.export
	);

